name: build-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.5'
          build-root-directory: 'app'
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '20'
          distribution: 'corretto'
      - name: Build with Gradle
        run: make build
      - name: Build and Push a JaCoCo report
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          JACOCO_SOURCE_PATH: "${{github.workspace}}/app/src/main/java"
        with:
          coverageCommand: make report
          debug: true